### PR TITLE
refactoring: get rid of this, concise conditions, renamed interface

### PR DESCRIPTION
**Pull request by kioviensis**
So, first of all, I found this decorator useful for me.

After code investigation and "demo play", I realized that I want to help simplify its API, to make it easier, as well as to get rid of unnecessary things that make it difficult to understand its essence

I want to explain my points consistently

1. **Rename interface**: the reason is to understand it faster. Basically, we've already SimpleChange, and the difference between them is only generic typing of the value. 

2. **This**: that part is the most important in this change. We don't _this_ at all (except when we invoke callback with .call method). 
All we need is using JS closures

3. **Small refactoring**: 
-  the way of condition `isFirstChange === undefined` is super cool. It's not about lines of code. It's about how you understand conditions. It's totally ok from my sight
- you had the code with condition (below). 
I didn't understand the first condition. Why it was there?
If you can explain why I'll return it easlily.
```typescript
// No operation if new value is same as old value
 if (!this[isFirstChangeKey] && this[cachedValueKey] === value) {
    return;
  }
```
- assignment before declaring simpleChange object. I found it unnecessary. We can without other efforts declare simpleChange, after that set the new cachedValue.

I'll gladly answer on any question

### CODE REVIEW

**Comment by zhaosiyang** [comment]
Hi Max, thanks for contributing.
1. I am ok with changing the interface name. However it's not a huge issue, and changing the interface name will break the existing code if people upgrade the package.
2. We absolutely need `this`. For your version, if we have multiple instance of the class, they would share the same cached value. TBH that was a mistake I made when implementing this code.
3. `!this[isFirstChangeKey]` means if it's first change, there is no "old value" to compare with.
Happy to discuss further!
Cheers!

**Comment by kioviensis** [comment]
Thanks for response)

1. Yeah, you're right.
But, I still recommend rename it, and the reason is obvious. For example, you need to have them both `SimpleChange` from **@angular/core** and `SimpleChange` from your package. And it would be perfect when developers will have the opportunity to manipulate those interfaces faster and clearer
And one more but, I don't push you on that. If you feel that we need to skip it - ok, not a big deal

2. Oh! Yeap, I saw your last commit in _master_. Can you please provide a short example of that case? It would help me a lot

3. Is it a protection of case when newValue on firstChange is undefined? But if it is undefined, do we need to trigger callback? I don't think so. Seems like redundant.
So, the condition of `cachedValue === nextValue` must working pretty good.

**Comment by zhaosiyang** [comment]
2. Let's say we have a `CounterComponent` with 
```
@OnChange(function(value) {console.log('n' is changed to, value)})
@Input() n: number
```
In your app.component.html, if you have this
```
<counter-component [n]="n1"></counter-component>
<counter-component [n]="n2"></counter-component>
```
and in your app.component.ts, you have this
```
onButton1Click() {
    n1 += 1;
}
onButton2Click() {
    n2 += 1;
}
```
You will see both of your two counter components will update n.

3. If we first set the value to be `undefined`, as we changed `isFirstChange` to be true, I would consider a "change event" is fired and thus the callback function should be triggered.
You also have a valid point that callback should not be triggered, but in this case, I will also avoid updating `isFirstChange` to true. 
So my point is that we should either do both or do nothing. I am fine with either. Neither of them will cause any problem :)

**Comment by kioviensis** [comment]
2. Much thanks!) After debugging, I understood that getter gives us unexpected (for us) value.

Btw, today I've been designing a new approach to handle it properly. 
I'll deliver it very soon.

3. As for me, it is redundant, because before the first change that value is already undefined. 
I checked how it handles Angular. Framework fires event on first change, even it is undefined and I understand why.

We can do like 
```typescript
@Input() name = 'John Doe'
```
```html
<app-component [name]="undefined"></app-component>
```
It will reassign `name` prop to `undefined`. That's why Angular fires event even on first change with undefined to prevent mistakes.

In our case, even if we assign it 
`@Input() name = 'John Doe'`
we're safe

**Comment by kioviensis** [comment]
btw, I propose you to create a new branch for the next release. 
I can add unit tests for this decorator in that branch.

**Comment by kioviensis** [comment]
yeah, ready

So, I want to make a few points

I implemented a structure that aggregates components information (references, inputs data, and isFirstChange)

From this moment, we don't mutate `this`. We simply register it in our structure and get its information on demand

We've made it a bit more difficult, to leave components cleaner as if we hadn't used `OnChange` decorator

**Comment by kioviensis** [comment]
@saithis thanks, nice catch

I'll try to change it with WeakSet/WeakMap

**Comment by kioviensis** [comment]
wow, it was tough
and I'm a bit disappointed 

Essentially, I came up with a solution when we still need mutation
I add  "private" props it might be a bit cleaner

perhaps this request becomes a matter of taste, and not of meaning

**Comment by zhaosiyang** [comment]
Thanks for contributing. I am closing the PR as it is going too far without a clear goal of what problem to solve. Please create another issue/PR if you have better ideas. Cheers

**Pull request closed without merging**
